flowchart LR
    HB[Hull Breach]
    HB -->|east| St[Stables]
    St -->|south| Sto["Storage
    giant electromagnet"]
    Sto -->|south| Ar["Arcade
    hologram"]
    HB -->|west| SL[Science Lab]
    SL -->|north| HCF["Hot Chocolate Fountain
    molten lava"]
    HCF -->|north| GWC["Gift Wrapping Center
    infinite loop"]
    GWC -->|west| Ha["Hallway
    semiconductor"]
    HCF -->|west| Pa[Passages]
    Pa -->|north| Co[Corridor]
    Pa -->|south| CQ["Crew Quarters
    hypercube"]
    SL -->|west| Ho["Holodeck
    antenna"]
    Ho -->|south| Ki["Kitchen
    spool of cat6"]
    Ho -->|west| WDM["Warp Drive Maintenance
    photons"]
    WDM -->|south| Na["Navigation
    escape pod"]
    Na -->|south| SC["Security Checkpoint"]
    HB -->|south| Ob["Observatory
    mouse"]
    Ob -->|east| En["Engineering
    shell"]
    Ob -->|west| SB["Sick Bay
    whirled peas"]
