import express from "express";
import * as Vite from "vite";
import type { SSRContextValue } from "@/context/SSRContext";

export async function createServer(
  root = process.cwd(),
  hmrPort?: number,
): Promise<{ app: express.Express }> {
  const app = express();

  const viteServer = await Vite.createServer({
    root,
    logLevel: "info",
    server: {
      middlewareMode: true,
      watch: {
        // During tests we edit the files too fast and sometimes chokidar
        // misses change events, so enforce polling for consistency
        usePolling: true,
        interval: 100,
      },
      hmr: {
        ...(hmrPort && { port: hmrPort }),
      },
    },
    appType: "custom",
  });
  app.use(viteServer.middlewares);

  app.use("*_", async (req, res) => {
    try {
      const url = req.originalUrl;

      const { render } = (await viteServer.ssrLoadModule(
        "/src/server-entry.tsx",
      )) as typeof import("../src/server-entry");

      const context: SSRContextValue = {};
      const html = await render(url, context, {
        bootstrapModules: ["/@vite/client", "/src/client-entry.tsx"],
        stylesheets: [],
      });

      res
        .status(Number(context.status ?? 200))
        .set({ "Content-Type": "text/html" })
        // Important: do not use viteServer.transformIndexHtml here, because
        // the HTML is entirely generated by React and we need it to stay as-is
        .end(html);
    } catch (e) {
      console.log("SSR error on path", req.originalUrl);
      if (!(e instanceof Error)) {
        console.log(e);
        throw e;
      }
      viteServer.ssrFixStacktrace(e);
      console.log(e);
      res.status(500).end(e.stack);
    }
  });

  return { app };
}

void createServer().then(({ app }) =>
  app.listen(5173, () => {
    console.log("Dev server started on http://localhost:5173");
  }),
);
